//
//  PeriodicTableStudyBuddyApp.swift
//  PeriodicTableStudyBuddy
//
//  Created by Christopher Francisco on 2/9/22.
//

import SwiftUI

@main
struct PeriodicTableStudyBuddyApp: App {
    
    init() {
        // significantly reduces element buttons from being toggled while spamming hard
        UIView.appearance().isMultipleTouchEnabled = false
        UIView.appearance().isExclusiveTouch = true
        UIButton.appearance().isMultipleTouchEnabled = false
        UIButton.appearance().isExclusiveTouch = true
        UILabel.appearance().isMultipleTouchEnabled = false
        UILabel.appearance().isExclusiveTouch = true
    }
    
    //let sk:ScreenKit = ScreenKit.shared
    @StateObject var info = AppStateInfo()
    
    var body: some Scene {
        WindowGroup {
            ZStack {
                IntroView()
                HomeView( info: info)
                ElementsView( info: info)
                    .zIndex(info.selectingElements ? 5 : 0)
                MasteringView( info: info)
                    .zIndex(info.selectingElements ? 0 : 5)
            }
        }
    }
}

@MainActor class AppStateInfo: ObservableObject {
    @Published var selectingElements:Bool = false
    @Published var onHomeScreen:Bool = true
    
    // the following array of dictionaries has been generated by DataScraper.swift
    // no f   ing way i was going to type that one by one
    @Published var elementsData:[[String:String]] =
    [["Symbol": "H", "Name": "Hydrogen", "Selected": "F", "AtomicNumber": "1"], ["Symbol": "He", "Selected": "F", "Name": "Helium", "AtomicNumber": "2"], ["AtomicNumber": "3", "Symbol": "Li", "Name": "Lithium", "Selected": "F"], ["Selected": "F", "Symbol": "Be", "Name": "Beryllium", "AtomicNumber": "4"], ["Symbol": "B", "Selected": "F", "Name": "Boron", "AtomicNumber": "5"], ["AtomicNumber": "6", "Selected": "F", "Name": "Carbon", "Symbol": "C"], ["AtomicNumber": "7", "Symbol": "N", "Selected": "F", "Name": "Nitrogen"], ["Selected": "F", "Symbol": "O", "AtomicNumber": "8", "Name": "Oxygen"], ["AtomicNumber": "9", "Symbol": "F", "Name": "Fluorine", "Selected": "F"], ["Selected": "F", "Symbol": "Ne", "Name": "Neon", "AtomicNumber": "10"], ["Symbol": "Na", "Name": "Sodium", "AtomicNumber": "11", "Selected": "F"], ["AtomicNumber": "12", "Symbol": "Mg", "Name": "Magnesium", "Selected": "F"], ["Symbol": "Al", "Name": "Aluminium", "Selected": "F", "AtomicNumber": "13"], ["AtomicNumber": "14", "Name": "Silicon", "Selected": "F", "Symbol": "Si"], ["AtomicNumber": "15", "Selected": "F", "Symbol": "P", "Name": "Phosphorus"], ["Selected": "F", "Name": "Sulfur", "AtomicNumber": "16", "Symbol": "S"], ["AtomicNumber": "17", "Selected": "F", "Symbol": "Cl", "Name": "Chlorine"], ["Symbol": "Ar", "Name": "Argon", "Selected": "F", "AtomicNumber": "18"], ["Selected": "F", "AtomicNumber": "19", "Symbol": "K", "Name": "Potassium"], ["Name": "Calcium", "AtomicNumber": "20", "Selected": "F", "Symbol": "Ca"], ["Name": "Scandium", "Symbol": "Sc", "Selected": "F", "AtomicNumber": "21"], ["AtomicNumber": "22", "Selected": "F", "Name": "Titanium", "Symbol": "Ti"], ["Symbol": "V", "AtomicNumber": "23", "Name": "Vanadium", "Selected": "F"], ["AtomicNumber": "24", "Symbol": "Cr", "Selected": "F", "Name": "Chromium"], ["Name": "Manganese", "Symbol": "Mn", "Selected": "F", "AtomicNumber": "25"], ["Name": "Iron", "Symbol": "Fe", "Selected": "F", "AtomicNumber": "26"], ["AtomicNumber": "27", "Symbol": "Co", "Selected": "F", "Name": "Cobalt"], ["Selected": "F", "AtomicNumber": "28", "Name": "Nickel", "Symbol": "Ni"], ["Symbol": "Cu", "Selected": "F", "Name": "Copper", "AtomicNumber": "29"], ["Symbol": "Zn", "AtomicNumber": "30", "Name": "Zinc", "Selected": "F"], ["Selected": "F", "Name": "Gallium", "Symbol": "Ga", "AtomicNumber": "31"], ["AtomicNumber": "32", "Selected": "F", "Name": "Germanium", "Symbol": "Ge"], ["Symbol": "As", "AtomicNumber": "33", "Selected": "F", "Name": "Arsenic"], ["Selected": "F", "Name": "Selenium", "AtomicNumber": "34", "Symbol": "Se"], ["Selected": "F", "Symbol": "Br", "AtomicNumber": "35", "Name": "Bromine"], ["Symbol": "Kr", "Selected": "F", "Name": "Krypton", "AtomicNumber": "36"], ["Symbol": "Rb", "Selected": "F", "AtomicNumber": "37", "Name": "Rubidium"], ["AtomicNumber": "38", "Selected": "F", "Symbol": "Sr", "Name": "Strontium"], ["AtomicNumber": "39", "Name": "Yttrium", "Symbol": "Y", "Selected": "F"], ["Selected": "F", "Name": "Zirconium", "Symbol": "Zr", "AtomicNumber": "40"], ["Symbol": "Nb", "Selected": "F", "Name": "Niobium", "AtomicNumber": "41"], ["Selected": "F", "Name": "Molybdenum", "AtomicNumber": "42", "Symbol": "Mo"], ["Symbol": "Tc", "AtomicNumber": "43", "Selected": "F", "Name": "Technetium"], ["AtomicNumber": "44", "Name": "Ruthenium", "Selected": "F", "Symbol": "Ru"], ["Name": "Rhodium", "Symbol": "Rh", "Selected": "F", "AtomicNumber": "45"], ["AtomicNumber": "46", "Selected": "F", "Symbol": "Pd", "Name": "Palladium"], ["Name": "Silver", "Selected": "F", "AtomicNumber": "47", "Symbol": "Ag"], ["Selected": "F", "Symbol": "Cd", "AtomicNumber": "48", "Name": "Cadmium"], ["Selected": "F", "Symbol": "In", "Name": "Indium", "AtomicNumber": "49"], ["AtomicNumber": "50", "Symbol": "Sn", "Name": "Tin", "Selected": "F"], ["Selected": "F", "Symbol": "Sb", "Name": "Antimony", "AtomicNumber": "51"], ["Selected": "F", "Symbol": "Te", "Name": "Tellurium", "AtomicNumber": "52"], ["Symbol": "I", "Selected": "F", "Name": "Iodine", "AtomicNumber": "53"], ["Symbol": "Xe", "Selected": "F", "AtomicNumber": "54", "Name": "Xenon"], ["Selected": "F", "Name": "Caesium", "AtomicNumber": "55", "Symbol": "Cs"], ["Selected": "F", "AtomicNumber": "56", "Symbol": "Ba", "Name": "Barium"], ["Name": "Lanthanum", "Symbol": "La", "Selected": "F", "AtomicNumber": "57"], ["Name": "Cerium", "AtomicNumber": "58", "Selected": "F", "Symbol": "Ce"], ["Selected": "F", "Symbol": "Pr", "AtomicNumber": "59", "Name": "Praseodymium"], ["AtomicNumber": "60", "Selected": "F", "Symbol": "Nd", "Name": "Neodymium"], ["Symbol": "Pm", "AtomicNumber": "61", "Selected": "F", "Name": "Promethium"], ["Name": "Samarium", "Selected": "F", "AtomicNumber": "62", "Symbol": "Sm"], ["Symbol": "Eu", "Selected": "F", "Name": "Europium", "AtomicNumber": "63"], ["Name": "Gadolinium", "Selected": "F", "AtomicNumber": "64", "Symbol": "Gd"], ["Name": "Terbium", "Symbol": "Tb", "AtomicNumber": "65", "Selected": "F"], ["AtomicNumber": "66", "Name": "Dysprosium", "Symbol": "Dy", "Selected": "F"], ["AtomicNumber": "67", "Selected": "F", "Name": "Holmium", "Symbol": "Ho"], ["Selected": "F", "Name": "Erbium", "AtomicNumber": "68", "Symbol": "Er"], ["AtomicNumber": "69", "Symbol": "Tm", "Selected": "F", "Name": "Thulium"], ["Symbol": "Yb", "AtomicNumber": "70", "Selected": "F", "Name": "Ytterbium"], ["Selected": "F", "Symbol": "Lu", "Name": "Lutetium", "AtomicNumber": "71"], ["Name": "Hafnium", "Symbol": "Hf", "Selected": "F", "AtomicNumber": "72"], ["AtomicNumber": "73", "Symbol": "Ta", "Selected": "F", "Name": "Tantalum"], ["Symbol": "W", "AtomicNumber": "74", "Name": "Tungsten", "Selected": "F"], ["AtomicNumber": "75", "Name": "Rhenium", "Selected": "F", "Symbol": "Re"], ["Selected": "F", "Symbol": "Os", "Name": "Osmium", "AtomicNumber": "76"], ["Name": "Iridium", "Selected": "F", "AtomicNumber": "77", "Symbol": "Ir"], ["Name": "Platinum", "Selected": "F", "AtomicNumber": "78", "Symbol": "Pt"], ["Selected": "F", "AtomicNumber": "79", "Symbol": "Au", "Name": "Gold"], ["Symbol": "Hg", "Name": "Mercury", "AtomicNumber": "80", "Selected": "F"], ["AtomicNumber": "81", "Symbol": "Tl", "Selected": "F", "Name": "Thallium"], ["Symbol": "Pb", "AtomicNumber": "82", "Name": "Lead", "Selected": "F"], ["Selected": "F", "Symbol": "Bi", "AtomicNumber": "83", "Name": "Bismuth"], ["Selected": "F", "AtomicNumber": "84", "Symbol": "Po", "Name": "Polonium"], ["AtomicNumber": "85", "Name": "Astatine", "Selected": "F", "Symbol": "At"], ["Name": "Radon", "Selected": "F", "Symbol": "Rn", "AtomicNumber": "86"], ["AtomicNumber": "87", "Selected": "F", "Symbol": "Fr", "Name": "Francium"], ["Name": "Radium", "Selected": "F", "AtomicNumber": "88", "Symbol": "Ra"], ["Selected": "F", "Name": "Actinium", "AtomicNumber": "89", "Symbol": "Ac"], ["Selected": "F", "AtomicNumber": "90", "Name": "Thorium", "Symbol": "Th"], ["Symbol": "Pa", "Selected": "F", "AtomicNumber": "91", "Name": "Protactinium"], ["AtomicNumber": "92", "Symbol": "U", "Name": "Uranium", "Selected": "F"], ["Selected": "F", "Symbol": "Np", "AtomicNumber": "93", "Name": "Neptunium"], ["Name": "Plutonium", "Selected": "F", "Symbol": "Pu", "AtomicNumber": "94"], ["Name": "Americium", "Selected": "F", "AtomicNumber": "95", "Symbol": "Am"], ["Symbol": "Cm", "AtomicNumber": "96", "Selected": "F", "Name": "Curium"], ["Selected": "F", "Symbol": "Bk", "Name": "Berkelium", "AtomicNumber": "97"], ["Selected": "F", "Symbol": "Cf", "AtomicNumber": "98", "Name": "Californium"], ["Symbol": "Es", "Name": "Einsteinium", "Selected": "F", "AtomicNumber": "99"], ["Name": "Fermium", "Symbol": "Fm", "Selected": "F", "AtomicNumber": "100"], ["AtomicNumber": "101", "Symbol": "Md", "Selected": "F", "Name": "Mendelevium"], ["Symbol": "No", "Name": "Nobelium", "Selected": "F", "AtomicNumber": "102"], ["Selected": "F", "Symbol": "Lr", "AtomicNumber": "103", "Name": "Lawrencium"], ["Symbol": "Rf", "AtomicNumber": "104", "Selected": "F", "Name": "Rutherfordium"], ["Symbol": "Db", "AtomicNumber": "105", "Selected": "F", "Name": "Dubnium"], ["AtomicNumber": "106", "Selected": "F", "Name": "Seaborgium", "Symbol": "Sg"], ["Name": "Bohrium", "AtomicNumber": "107", "Symbol": "Bh", "Selected": "F"], ["Selected": "F", "AtomicNumber": "108", "Name": "Hassium", "Symbol": "Hs"], ["Name": "Meitnerium", "Selected": "F", "AtomicNumber": "109", "Symbol": "Mt"], ["Name": "Darmstadtium", "Symbol": "Ds", "AtomicNumber": "110", "Selected": "F"], ["Selected": "F", "AtomicNumber": "111", "Name": "Roentgenium", "Symbol": "Rg"], ["Selected": "F", "Symbol": "Cn", "Name": "Copernicium", "AtomicNumber": "112"], ["Symbol": "Nh", "Name": "Nihonium", "AtomicNumber": "113", "Selected": "F"], ["Symbol": "Fl", "Name": "Flerovium", "AtomicNumber": "114", "Selected": "F"], ["Selected": "F", "Symbol": "Mc", "AtomicNumber": "115", "Name": "Moscovium"], ["Name": "Livermorium", "AtomicNumber": "116", "Symbol": "Lv", "Selected": "F"], ["AtomicNumber": "117", "Name": "Tennessine", "Symbol": "Ts", "Selected": "F"], ["AtomicNumber": "118", "Symbol": "Og", "Selected": "F", "Name": "Oganesson"]]
    
    @Published var questionAnswer:[[String]] = []
    
    func getSymbol(atomicNumber:Int) -> String {
        return elementsData[atomicNumber - 1]["Symbol"]!
    }
    
    func getName(atomicNumber:Int) -> String {
        return elementsData[atomicNumber - 1]["Name"]!
    }
    
    func getIsSelected(atomicNumber:Int) -> String {
        return elementsData[atomicNumber - 1]["Selected"]!
        
    }
    
    func setIsSelected(atomicNumber:Int, isSelected:String) {
        elementsData[atomicNumber - 1]["Selected"] = isSelected
    }
    
    func generateSelectedElementsQuestions() {
        for elementData in self.elementsData {
            if (elementData["Selected"] == "T") {
                generateAtomicNumberQuestion(elementData: elementData)
                generateSymbolQuestion(elementData: elementData)
            }
        }
        print(self.questionAnswer)
        
    }
    
    func generateAtomicNumberQuestion(elementData:[String:String]) {
        var question:String = "What is the atomic number of \(elementData["Name"]!)?"
        var answer:String = elementData["AtomicNumber"]!
        self.questionAnswer.append([question, answer])
        question = "Which element has the atomic number \(elementData["AtomicNumber"]!)?"
        answer = elementData["Name"]!
        self.questionAnswer.append([question, answer])
    }
    
    func generateSymbolQuestion(elementData:[String: String]) {
        var question:String = "What is the symbol of \(elementData["Name"]!)?"
        var answer:String = elementData["Symbol"]!
        self.questionAnswer.append([question, answer])
        question = "Which element has the symbol \(elementData["Symbol"]!)?"
        answer = elementData["Name"]!
        self.questionAnswer.append([question, answer])
        
    }
}
